# Generated by Django 4.0.1 on 2022-01-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='categories',
        ),
    ]
