# Generated by Django 4.0.1 on 2022-01-13 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_donation_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='categories',
            field=models.ManyToManyField(through='main.DonationCategories', to='main.Category'),
        ),
        migrations.AddField(
            model_name='donationcategories',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.donation'),
        ),
    ]
