# Generated by Django 4.0.1 on 2022-01-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_donation_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='date_taken',
            field=models.DateField(null=True),
        ),
    ]
