# Generated by Django 4.0.1 on 2022-01-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_donation_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='time_taken',
            field=models.TimeField(null=True),
        ),
    ]
